server:
  port: 4001
spring:
  application:
    name: service-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/*
      serviceId: eureka-consumer
    api-b:
      path: /api-b/*
      serviceId: service-feign