server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YoGhurt111/SpringCloudConfig
          search-paths: config_test
          username: YoGhurt111
          password: YU19960223
      label: master